/*
	see comment in OSGCOMUI.h

	This file is automatically generated by the build system,
	which tries to know what options are valid in what
	combinations. Avoid changing this file manually unless
	you know what you're doing.
*/

#import <Cocoa/Cocoa.h>
#include <CoreAudio/CoreAudio.h>
#include <AudioUnit/AudioUnit.h>
#include <OpenGL/gl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/param.h>
#include <sys/time.h>
#define UseAudioComp 0
#define MyNSPasteboardTypeString NSStringPboardType
#define MyNSEventModifierFlagCapsLock NSAlphaShiftKeyMask
#define MyNSEventModifierFlagShift NSShiftKeyMask
#define MyNSEventModifierFlagControl NSControlKeyMask
#define MyNSEventModifierFlagOption NSAlternateKeyMask
#define MyNSEventModifierFlagCommand NSCommandKeyMask
#define MyNSWindowStyleMaskBorderless NSBorderlessWindowMask
#define MyNSWindowStyleMaskTitled NSTitledWindowMask
#define MyNSWindowStyleMaskMiniaturizable NSMiniaturizableWindowMask
#define MyNSWindowStyleMaskClosable NSClosableWindowMask
#define MyNSEventTypeLeftMouseDown NSLeftMouseDown
#define MyNSEventTypeLeftMouseUp NSLeftMouseUp
#define MyNSEventTypeRightMouseDown NSRightMouseDown
#define MyNSEventTypeRightMouseUp NSRightMouseUp
#define MyNSEventTypeOtherMouseDown NSOtherMouseDown
#define MyNSEventTypeOtherMouseUp NSOtherMouseUp
#define MyNSEventTypeMouseMoved NSMouseMoved
#define MyNSEventTypeLeftMouseDragged NSLeftMouseDragged
#define MyNSEventTypeRightMouseDragged NSRightMouseDragged
#define MyNSEventTypeOtherMouseDragged NSOtherMouseDragged
#define MyNSEventTypeKeyDown NSKeyDown
#define MyNSEventTypeKeyUp NSKeyUp
#define MyNSEventTypeFlagsChanged NSFlagsChanged
#define MyNSEventTypeApplicationDefined NSApplicationDefined
#define MyNSAnyEventMask NSAnyEventMask

#define EnableDragDrop 1
#define MyAppIsBundle 1
#define WantOSGLUCCO 1

#define kStrAppName "Mini vMac"
#define kAppVariationStr "Blah Blob"
#define kStrCopyrightYear "2020"
#define kMaintainerName "unknown"
#define kStrHomePage "(unknown)"
