/*
	see comment in OSGCOMUI.h

	This file is automatically generated by the build system,
	which tries to know what options are valid in what
	combinations. Avoid changing this file manually unless
	you know what you're doing.
*/

/* adapt to current compiler/host processor */

#define MayInline __forceinline
#define MayNotInline __declspec(noinline)
#define SmallGlobals 0
#define cIncludeUnused 1
#define UnusedParam(p) (void) p

/* --- set up compiler options --- */

/* ignore integer conversion warnings */
#pragma warning(disable : 4244 4761 4018 4245 4024 4305)

/* ignore unused inline warning */
#pragma warning(disable : 4514 4714)

/* ignore unary minus operator applied to unsigned type warning */
#pragma warning(disable : 4146)

/* more warnings */
#pragma warning(disable : 4127 4701)

/* --- integer types ---- */

typedef unsigned char ui3b;
#define HaveRealui3b 1

typedef signed char si3b;
#define HaveRealsi3b 1

typedef unsigned short ui4b;
#define HaveRealui4b 1

typedef short si4b;
#define HaveRealsi4b 1

typedef unsigned int ui5b;
#define HaveRealui5b 1

typedef int si5b;
#define HaveRealsi5b 1

#define HaveRealui6b 0
#define HaveRealsi6b 0

/* --- integer representation types ---- */

typedef ui3b ui3r;
#define ui3beqr 1

typedef si3b si3r;
#define si3beqr 1

typedef ui4b ui4r;
#define ui4beqr 1

typedef si4b si4r;
#define si4beqr 1

typedef ui5b ui5r;
#define ui5beqr 1

typedef si5b si5r;
#define si5beqr 1

typedef signed __int64 si6r;
typedef signed __int64 si6b;
typedef unsigned __int64 ui6r;
typedef unsigned __int64 ui6b;
#define LIT64(a) a##Ui64
