/*
	see comment in OSGCOMUI.h

	This file is automatically generated by the build system,
	which tries to know what options are valid in what
	combinations. Avoid changing this file manually unless
	you know what you're doing.
*/

#define _CRT_SECURE_NO_DEPRECATE 1

/* ignore warning generated by system includes */
#pragma warning(push)
#pragma warning(disable : 4201 4115 4214)

#include <SDL2/SDL.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* restore warnings */
#pragma warning(pop)

#define EnableDragDrop 1
#define WantOSGLUSDL 1

#define kStrAppName "Mini vMac"
#define kAppVariationStr "Blah Blob"
#define kStrCopyrightYear "2020"
#define kMaintainerName "unknown"
#define kStrHomePage "(unknown)"
